import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseCountries } from "./parse-countries";

const input =
  process.argv[2] ??
  fileURLToPath(new URL("../data/iso-3166.xml", import.meta.url));
const output =
  process.argv[3] ?? fileURLToPath(new URL("../src/data.ts", import.meta.url));
const records = parseCountries(readFileSync(input, "utf8"));

const header = [
  "// Generated by npm run iso:ingest-xml. Do not edit manually.",
  "// Source: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes",
  "// Adaptation: four-field subset; XML attributes renamed to TypeScript properties.",
  "// Data: CC BY-SA 4.0, lukes and contributors. See NOTICE.md and data/LICENSE.md.",
  "// https://creativecommons.org/licenses/by-sa/4.0/",
  "",
].join("\n");

writeFileSync(
  output,
  `${header}export const countryData = ${JSON.stringify(records, null, 2)} as const;\n`,
);
console.log(`Generated ${records.length} countries in ${output}`);
